### PR TITLE
Refactor internals. Fix finalizers.

### PR DESCRIPTION
**Pull request by TarasLevelUp**
What was the purpose of such a refactor:
* Remove `async` tasks from QueueReader and ChannelActor so we don't need to use _TEST hack and for speed reasons #44 .
* Add more straight finalisation. When connection closes it should close (willingly or not) all channels and consumers must be notified. So we finalise in order connection -> channel -> consumer. Will help with #34 . 

In the process I saw some places, that could be optimised:
* QueueReader does not need a heavy [asyncio.Queue](https://hg.python.org/cpython/file/3.5/Lib/asyncio/queues.py#l29).
* Synchroniser can be written easily without OrderedDict, which is quite heavy if used so much. Also made sure it raises same error, as it was killed with.
* Added FrowControl to Protocol. This will give the ability to `drain()` from transport writes. I use it on close, so we inform server before closing connection (sending CloseOK may not be enough if buffers are full.)
* Added some base classes for for closed connection/channel errors, but the names aren't too bright...

Feel free to comment on  things, you consider needs changing. I think the way I pass ConnectionClose to be dispatched to all Writers is a bit ugly and Synchroniser's way to save future for more than 1 method can be written more cleanly.

### CODE REVIEW

**Comment by TarasLevelUp** [comment]
Will add some tests to fix up coverage at weekend. Wanted to get feedback on code changes as soon as possible, so didn't look that deem on coverage, sorry.

**Comment by benjamin-hodgson** [comment]
Upon a skim-read this code looks mostly good, but the scope of this pull request makes it hard to review. Do you think you could split up your changes into logical units and submit them as separate patches? For example, one PR for the `QueueReader` optimisation, another for the flow control stuff, etc. This will make it easier for me to review and will simplify the commit history.

**Comment by TarasLevelUp** [comment]
Yes, I can. Will do on weekend then

**Comment by benjamin-hodgson** [comment]
Oh that's great, thanks. Looking forward to it!

**Pull request closed without merging**
