### PR TITLE
Queue should not bind to default exchange

### LINKED ISSUE #77: Using default exchange
So I have seen that when the exchange name is not provided, the code is prepared to return a the default exchange, but I have been unable to use the example modified to use the default exchange.

```
    connection = yield from asynqp.connect()

    channel = yield from connection.open_channel()

    exchange = yield from channel.declare_exchange('', 'direct')
    queue = yield from channel.declare_queue('default')

    # It will throw an exception here
    # if exchange.name: # skip the exception here
    yield from queue.bind(exchange, 'default')

    msg = asynqp.Message(body)
    # If the bind is skipped depending on exchange.name, it will except here
    exchange.publish(msg, routing_key)

    yield from channel.close()
    yield from connection.close()
```

The first exception will be an `asynqp.spec.AccessRefused`, which goes accordingly to the amqp spec, although I believe that asynqp should implement additional logic inside when using the default exchange.

The second exception when publishing the message is:

```
ERROR:asyncio:Exception in callback BasicReturnConsumer.default_behaviour(<asynqp.messa...x7f2f18b0c198>)
handle: <Handle BasicReturnConsumer.default_behaviour(<asynqp.messa...x7f2f18b0c198>)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/javier/ve3/lib/python3.5/site-packages/asynqp/channel.py", line 415, in default_behaviour
    raise UndeliverableMessage(msg)
asynqp.exceptions.UndeliverableMessage: <asynqp.message.IncomingMessage object at 0x7f2f18b0c198>
ERROR:asyncio:Exception in callback _SelectorTransport._call_connection_lost(None)
handle: <Handle _SelectorTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 610, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "/home/javier/ve3/lib/python3.5/site-packages/asynqp/protocol.py", line 53, in connection_lost
    raise ConnectionClosedError('The connection was closed')
```

Which I believe is because bind() should be called. I think I am missing something, but I don't know exactly what.

I think it is related to https://github.com/celery/kombu/issues/209

### PR DESCRIPTION
**Pull request by txomon**
To fix #77

### CODE REVIEW

**Comment by txomon** [comment]
Probably I would need to write a test also to assert that the default exchange is being treated as an exception...

**Comment by txomon** [comment]
Now it should be ready for merging.

**Comment by benjamin-hodgson** [comment]
As far as I recall, RabbitMQ doesn't allow you to bind a queue to the default exchange. The default exchange will always send the message to the queue named by the routing key. So you shouldn't really be attempting to bind your queue to the default exchange in the first place.

The debate here, therefore, is whether `asynqp` should allow you to bind a queue to the default exchange (but silently do nothing) or throw an exception. A quick survey of other clients shows that [Pika doesn't appear to handle it at all](https://github.com/pika/pika/blob/master/pika/channel.py#L752-L776) and [Kombu silently does nothing](https://github.com/celery/kombu/blob/5a76eddd2b0ee4670e565088c556c06c0ff740ab/kombu/abstract.py#L77-L83).

I have a slight preference for throwing an exception when you bind to the default exchange. Better to make people think about what they're doing. (The existing error message could certainly be improved upon, though.)

**Comment by txomon** [comment]
Indeed, it doesn't allow you to bind. I took this implementation idea from kombu.

In my case, I would make it transparent, because that way you can use it generically. My code for example, is running in an executor that has different kind of actions builtin, and one of them is queueing a message in an AMQP queue.

Therefore the idea of making the queue bind skip silently. Without this patch, I would have needed to create the QueueBinding manually to avoid the publishing fail, which I am not really in favor of.

**Comment by Drizzt1991** [comment]
Hi, I too am in favor of receiving an Exception upon calling a bind on default exchange. By specification you don't need to do that at all. I think it's better for the user to think 2-ce what he is doing.

**Comment by txomon** [comment]
@Drizzt1991 This code could be replaced by checking in `publish()` if the exchange is the default or not, and not raising an exception if there is no queue binding and it's the default exchange.

I am ok with any solution as long as it doesn't mean another call to asynqp, although I still prefer the transparent way because that way you don't need if/else clause to bind or not.

**Comment by benjamin-hodgson** [comment]
Let's throw an exception from `bind` then. I'm going to close this PR

**Comment by txomon** [comment]
@benjamin-hodgson I don't see any update in master that does the exception thing, nor a solution to not generating manually a QueueBinding...

**Comment by benjamin-hodgson** [comment]
@txomon Apologies, looks like this slipped through the cracks. [Fixed in master](https://github.com/benjamin-hodgson/asynqp/commit/59e839f81f4e230370a5a13b4e2c00b07ce73d08)

**Comment by txomon** [comment]
No worries, will check how you managed ;)

**Pull request closed without merging**
