### PR TITLE
Added server side consumer cancel

### PR DESCRIPTION
**Pull request by Drizzt1991**
https://www.rabbitmq.com/consumer-cancel.html

### CODE REVIEW

**Comment by benjamin-hodgson** [comment]
This is good. The one thing I think we should do is check whether the server supports `consumer_cancel_notify` at startup

**Comment by Drizzt1991** [comment]
I don't really understand what to do if it doesn't. It's not a problem to us I think.

**Comment by Drizzt1991** [comment]
Or you want something like:
``connection.capabilities``?

**Comment by Drizzt1991** [comment]
Rebases. What about the `connection.capabilities` question? Did you expect something like that?

**Comment by benjamin-hodgson** [comment]
No, I think you're right. A server which doesn't support `consumer_cancel_notify` won't be sending us cancel requests, so there's no need. It'll just be dead code. We might want to expose `connection.capabilities` for querying by clients but I don't think there's any pressing need for it

**Comment by Drizzt1991** [comment]
Rebased. This should be OK to merge.

**Comment by Drizzt1991** [comment]
rebased

**Pull request merged**
