### PR TITLE
Timestamp

### PR DESCRIPTION
**Pull request by fwiesel**
I simply followed the spec, but didn't do a validation with another implementation.

### CODE REVIEW

**Comment by fwiesel** [comment]
The first commit is actually a small fix to my last pull request. Sorry for mixing it this pull request.

**Comment by benjamin-hodgson** [comment]
Your code looks good to me. [The Travis build is failing](https://travis-ci.org/benjamin-hodgson/asynqp/builds/65722457#L450) because it looks like it's attempting to compare `datetime`s that are almost-but-not-quite-equal. Do the tests work on your machine?

**Comment by fwiesel** [comment]
I missed something about the timezones, it seems. I will come back with a fix.

**Comment by benjamin-hodgson** [comment]
Great, thanks very much! :beer:

**Pull request merged**
