### PR TITLE
Fixed amqp properties reading. Had invalid flag checks.

### PR DESCRIPTION
**Pull request by Drizzt1991**

### CODE REVIEW

**Comment by Drizzt1991** [comment]
Tried to receive msg's with property `content_encoding` but without `content_type` and it failed

**Comment by benjamin-hodgson** [comment]
Could you add a unit test please?

**Comment by TarasLevelUp** [comment]
Dou, yea, somehow forgot about that =). Will add, but later.

**Comment by Drizzt1991** [comment]
Added test.

**Comment by Drizzt1991** [comment]
Rebased

**Pull request merged**
